myblogapp/myblogapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblogapp/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns=[
  path('index/',views.index,name="index"),
  path('post_detail/<int:post_id>', views.post_detail,name="post_detail")
]

myblogapp/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    published = models.DateTimeField()
    image = models.ImageField(upload_to='media/')
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:30]

myblogapp/posts/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
# Create your views here.
def index(request):
  posts = Post.objects.order_by('-published').all()
  return render(request,'index.html', context={
    'posts' : posts
  })

def post_detail(request,post_id):
  post = get_object_or_404(Post, pk=post_id)
  return render(request,'post_detail.html', context={
    'post' : post
  })

myblogapp/templates/index.html
{% load static %}
<h1>HelloWorld</h1>
ようこそ画像！
<img src="{% static 'menu01.png' %}" alt="">
<br><br>

{% for post in posts %}
<a href ="{% url 'posts:post_detail' post_id=post.id %}">{{ post.title }}</a>
<br /><br />
{{ post.published }}
<img src="{{ post.image.url }}" class = "img-fluid rounded" style="max-height: 200px;" />
{{post.summary}}
<br /><br />
{% endfor %}

myblogapp/templates/post_detail.html
<!DOCTYPE html>
<html lang = "ja-jp">
<head>
  <title>???のブログ</title>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">???のブログ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.udemy.com/user/hirokiinoue/">Udemyプロフィール</a>
      </li>

    </ul>

  </div>
</nav>
<div class="container">
<br />
    <a href ="{% url 'posts:post_detail' post.id %}">{{ post.title }}</a>
    <br /><br />
    {{ post.published }}
    <br /><br />
    <img src="{{ post.image.url }}" class = "img-fluid rounded" style="max-height: 200px;" />
    <br /><br />
    {{ post.body }}
    <br /><br />

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </div>
</body>
</html>